### ISSUE TITLE
need help on my base

### ISSUE THREAD

**Issue by dschaf** [hooksteroid/D3D_ApexFeature#1]
hey i just added u on discord i have made my own internal base and i have it completed accept i need help with the device->
present hook part. sense when i inject i get device error its not the driver i made ive checked it in debug any help from anyone would be nice

**Comment by neicun** [comment]
stop pasting

**Comment by dschaf** [comment]
> stop pasting
i guess people who ask questions are pasters now...
how is that pasting i have my own base u clown besides that comment was  posted Jun 18 my cheat has been done along time ago you certainly arent innocent if ur on this page too 
btw dont go around calling people pasters when u have no idea who they are it will keep you from
 embarrassing yourself.
